#配置数据库的连接信息
#数据源配置
spring:
  application:
    name: this-web-management

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 1234

  servlet:
    multipart:
      #单个文件上传大小限制
      max-file-size: 10MB
      #最大请求大小限制
      max-request-size: 100MB
#mybatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启了驼峰命名映射的开关
    map-underscore-to-camel-case: true
#分页插件
pagehelper:
  reasonable: true
  helper-dialect: mysql
#日志配置
logging:
    level:
        org.springframework.jdbc.support.JdbcTransactionManager: debug


